---
title: "05-data-summary"
format: pdf
---

## Environment Setup

```{r setup}
#| include: false
#| warning: false
#| message: false

library(tidyverse)
library(here)
library(arrow)
library(patchwork)

loans <- read_parquet(here("data", "01-raw_data", "loans_NY.parquet"))
loans_NY <- read_parquet(here("data", "02-analysis_data", "loans_NY_clean.parquet"))
loans_NY_model_data <- readRDS(here("data", "02-analysis_data", "model_data.rds"))
```

```{r}
#| eval: FALSE
knitr::opts_chunk$set(
  cache = TRUE,
  cache.path = "cache/",  # Keeps your directory clean
  autodep = TRUE          # Automatically detects dependencies between chunks
)
```




```{r}
#| label: fig-dti
#| fig-cap: "Distribution of loan outcomes by debt-to-income (DTI) ratio categories (right)."
#| fig-width: 8
#| fig-height: 4
#| echo: false

# Debt-to-Income Ratio Distribution
plot_dti_count <- ggplot(loans_NY, aes(x = dti_bracket, fill = status)) +
  geom_bar() +
  scale_fill_manual(values = c("Approved" = "springgreen3", "Denied" = "firebrick2")) +
  theme_minimal() +
  theme(axis.text.x = element_text(angle = 90), 
        plot.title = element_text(hjust = 0.5), legend.position = "top") +
  labs(title = "Mortgage Application Decisions by \n Debt-to-Income Ratio Categories", 
       x = "Debt-to-Income Ratio (%)", y = "Count of Loans", fill = "Loan Decision")

plot_dti_prop <- ggplot(loans_NY, aes(x = dti_bracket, fill = status)) +
  geom_bar(position = "fill") +
  scale_fill_manual(values = c("Approved" = "springgreen3", "Denied" = "firebrick2")) +
  theme_minimal() +
  theme(axis.text.x = element_text(angle = 90), 
        plot.title = element_text(hjust = 0.5), legend.position = "top") +
  labs(title = "Mortgage Application Decisions by \n Debt-to-Income Ratio Categories", 
       x = "Debt-to-Income Ratio (%)", y = "Proportion of Loans", fill = "Loan Decision")

plot_dti_prop + plot_dti_count
```



```{r}
#| label: fig-geo-bank-dist
#| fig-cap: "Histograms showing the variation in mortgage denial rates at the county level (left) and the individual lending institution level (right)."
##| fig-width: 6
##| fig-height: 3
#| echo: false

# Calculate denial rate per county
plot_county <- loans_NY |>
  group_by(county_code) |>
  summarise(denial_rate = mean(denied), n = n()) |>
  ggplot(aes(x = denial_rate)) +
  geom_histogram(fill = "seagreen3", bins = 12) +
  scale_x_continuous(labels = scales::percent) +
  theme_minimal() +
  labs(
    title = "Mortgage Denial Rates \n Across NY Counties",
    x = "County Denial Rate (%)",
    y = "Number of Counties")

plot_banks <- loans_NY |>
  group_by(lender_id) |>
  summarise(denial_rate = mean(denied), n = n()) |>
  ggplot(aes(x = denial_rate)) +
  geom_histogram(fill = "indianred3", bins = 10)+
  theme_minimal() +
  labs(title = "New York Denial Rates \n Across Banks",
       x = "Bank Denial Rate (%)", y = "Number of banks")

plot_county + plot_banks
```


```{r}
plot_race_sex <- loans_NY |>
  group_by(race, sex) |>
  summarise(denial_rate = mean(denied), n = n(), .groups = "drop") |>
  # Filter for bins with enough data to be reliable
  filter(n > 50) |>
  ggplot(aes(x = reorder(sex, -denial_rate), y = denial_rate, fill = reorder(race, -denial_rate))) +
  geom_col(position = "dodge", alpha = 0.8, color = "gray30") +
  scale_fill_manual(values = c(
    "White"            = "wheat1",       
    "Asian"            = "wheat3",      
    "Joint"            = "tan2",        
    "Other/Multiracial"= "tan4",         
    "Black"            = "sienna4"       
  )) +
  scale_y_continuous(labels = scales::percent) +
  theme_minimal() +
  theme(axis.text.x = element_text(angle = 45, hjust = 1), legend.position = "top") +
  labs( title = "Denial Rates by Race and Sex", 
        x = "Sex Category", 
        y = "Denial Rate (%)",
        fill = "Race")
```



```{r}
#| label: fig-bank-gap
#| fig-cap: "Institutional denial gap (POC Rate - White Rate). Values above the 0% dashed line represent banks where POC applicants face higher denial rates than White applicants."
#| fig-width: 10
#| fig-height: 4
#| echo: false


# Calculate disparity gap for each Lender
lender_disparity <- loans_NY |>
  group_by(lender_id) |>
  summarise(
    total_apps = n(),
    white_apps = sum(applicant_poc == "White"),
    poc_apps = sum(applicant_poc == "POC/Non-White"),
    white_denial = mean(denied[applicant_poc == "White"], na.rm = TRUE),
    poc_denial = mean(denied[applicant_poc == "POC/Non-White"], na.rm = TRUE)
  ) |>
  filter(white_apps > 20, poc_apps > 20) |>
  mutate(denial_gap = poc_denial - white_denial)

plot_bank_gap <- ggplot(lender_disparity, aes(x = total_apps, y = denial_gap)) +
  geom_hline(yintercept = 0, linetype = "dashed", color = "gray20") +
  geom_point(color = "firebrick3", alpha = 0.5, size = 3) +
  scale_x_log10(labels = scales::comma) +
  scale_y_continuous(labels = scales::percent) +
  theme_minimal() +
  labs(title = "Denial Gap between Races by Bank",
    x = "Total Application Volume at Bank (Log Scale)",
    y = "Denial Gap (POC Rate - White Rate)")

plot_bank_gap + plot_race_sex
```